export default {
  IUmTHJiK: `Last {{count}} Hours `,
  AgkYiJkT: `Last {{count}} Hours `,
  lDSduKsa: `Last {{count}} Days `,
  KpzGiFsD: `Last {{count}} Days `,
  lLuqKPvM: `Custom `,
  uZmmnADI: `Now `,
  kWdIweAF: `End Time Must Be Later Than Start Time `,
  TMxVteBW: `Select a Time Before {{- time}} `,
  wuEeFODO: `Select a Time After {{- time}} `,
  PMHOOado: `Select an Option That Does Not Exceed {{- time}} `,
  kpzeKWmd: `Select an Option of at Least {{- time}} `,
  sPraBorJ: `Updating… `,
  NnsQwRKy: `Paused `,
  McwOQxLQ: `Click to Copy `,
  iJXYVbcx: `Close `,
  GJwpylCH: `None `,
  aXRnHjol: `Click to View Details `,
  cEFaqfsx: `Got It `,
  vGOpyGeG: `Acknowledgement `,
  jtiQEEbB: `Got It `,
  BlUWOiZv: `I hereby acknowledge that all accomplishments created during my employment with NetEase, resulting from performing my duties or primarily utilizing the company's resources, business information, know-how, confidential information, etc., (accomplishments include but are not limited to inventions, works, trademarks, technical secrets, business secrets, and other outputs produced using any tools such as software, equipment, and systems, regardless of their form or completion status) are the property of NetEase. This includes all intellectual property rights and other associated rights (such as trademark rights, patent rights, and copyrights, including their respective application rights).
The aforementioned accomplishments include those created independently, collaboratively with others, or inspired by my contributions. NetEase may, within its business scope, fully and freely use these achievements for production, operations, or transfer them to third parties. I shall not use these achievements in any form, except to perform my duties.
I agree to provide all necessary information and take all necessary actions as required by NetEase to assist in obtaining and exercising relevant intellectual property rights, ownership, or other interests. This includes application, registration, and filing. I irrevocably authorize NetEase and/or its authorized personnel to act on my behalf with full power of attorney (special authorization) to sign relevant documents and implement all legal actions.
My obligations under this acknowledgement shall continue to exist after the termination or revocation of my employment relationship with NetEase. `,
  nLcrZTCd: `For Internal Use Only. Not For External Distribution `,
  DvoQbZuo: `Required Field `,
  hTZdoMFp: `Only English letters (uppercase and lowercase), Chinese characters, numbers, dashes and underscores are allowed `,
  mmvCViFx: `Only English letters (uppercase and lowercase), numbers, dashes and underscores are allowed `,
  KZjaIfgQ: `Maximum Length: 50 Characters `,
  MFTNcgQs: `Enter a Positive Number `,
  AXifXqqu: `LoRA (Recommended) `,
  BMvjTvEl: `Image `,
  EEJOEoYC: `Training Set `,
  qfrQmkeu: `Private `,
  yYPrXzzo: `Managed `,
  ndONQYLB: `Shared `,
  zWHMzwVf: `Yes `,
  IDBEebqB: `No `,
  xBZsKowV: `Unable to create instance. Try refreshing the page. If the issue persists, please contact Liu Qi (liuqi17@corp.netease.com). `,
  iUWctqid: `Starting, please wait… `,
  REyvSfKA: `Image Class `,
  iuzaisdJ: `Select a Class First `,
  dFwIGuon: `Select a Class First `,
  AtFNByHe: `Class Switched `,
  tDWLzDhc: ` Image `,
  ENTNwdSS: ` Folder `,
  GXWrGXjf: `Unable to Delete `,
  snoNIQyq: `Deleted `,
  GBdATILj: `No Files Selected `,
  oTpiAfQF: `Evaluation Complete `,
  VpQZxeui: `Unable to Evaluate `,
  aOARMcOA: `Node Flow `,
  iWYniViz: `Delete the Selected {x} {y}? `,
  oVcxVLXd: `Creation Record `,
  BmskzaCL: `Stars `,
  GPfPHJiB: `Click Here to Deselect `,
  bbfhVpSz: `; Right Click to Download or Delete `,
  RjaRKqrR: `No More Data to Display `,
  KOzwCgQl: `Time Created `,
  jBxtaeve: `Dimensions `,
  MgRCEVYN: `Generation Method `,
  zmFIHrYx: `Image `,
  XXnYVLta: `Downloading... `,
  rXhlLWpz: `Parameters `,
  NBzqNpHw: `Parameters `,
  DGeyPYjZ: `Node Flow Info `,
  wXCRLChO: `Node Flow Info `,
  YfTcWaxk: `Information `,
  stmyyosy: `Information `,
  TITVzAOT: `Save as Prompt `,
  RXFXoPLi: `Creation Records Are Saved for up to 7 Days `,
  wOcYTCjA: `{x} Selected; `,
  HyKJJrtC: `Click and Drag to Select or Press Shift to Batch Select {x} `,
  YKWiMzGG: `Or `,
  JLUJyoLJ: `Press and Hold Shift `,
  vLNNqQpU: `Batch Select `,
  OzYfWGvb: `Download `,
  xScthtbG: `Delete `,
  LAsdQuvT: `Score `,
  kVnEvcDa: `OK `,
  mQKFzJMh: `Cancel `,
  zDXmZwMR: `See Error Details `,
  jRJeJCqW: `Deleted `,
  mYuQleai: `Downloading… `,
  gwKOdcXu: `No Files Selected `,
  DYZOpLkr: `Renamed `,
  yoZgfGXI: `Evaluation Complete `,
  LIYgOjfH: `Unable to Evaluate `,
  DuOEBjhL: `No More Data to Display `,
  tMVpolqF: `Reading Data… `,
  JQwdUQnL: `Delete the Selected {x} {y}? `,
  SwzKXCuR: `; Right Click to See More Options `,
  ggSvVYSW: `Training Set Preview `,
  aJBbRscI: `Select a Training Set `,
  ysJcWJFH: `Root Directory `,
  LEjrxYgS: `No Data Available `,
  aRFjGuBg: `Too Many Files. Click Download to View All Details `,
  brgEMyCr: `Assets `,
  daQONuaV: `Unable to Load. No Information Available for This Asset `,
  WUAILYjy: `Return to Asset Library `,
  lxcTjoIG: `Upload {x} `,
  isKSxEJH: `No Type Data `,
  FZSPkAtL: `Select a File to Move `,
  hpLpDaqk: `Unable to Select the Same Class `,
  yMhBmQzh: `Individual Image `,
  OVqpGonn: `Image Set `,
  MncygsqX: `IP Asset `,
  OFLetvgs: `General Asset `,
  vIgJgdFu: `Confidential Asset `,
  UIGodUtV: `Artwork Published `,
  kkyEnQpV: `Exit Editing Page? `,
  GMEGVYty: `Once you exit, the edited content will be lost. Exit anyway? `,
  eqAbMvqK: `Double Click to Select a Class `,
  VGAbNxpR: `Share to Muse `,
  pIVJivIa: `Cancel `,
  wsxEsJwd: `Uploading… `,
  kXlZVKXf: `Share `,
  cjOuktNM: `Select Library `,
  VdnDwCqw: `Library to Save in `,
  vRoyKXsJ: `Select a Library `,
  nGIOOPah: `Basic Information `,
  XeMOBywq: `Select Type `,
  NpksvHaq: `Title of Work `,
  PXzJTuyj: `When individual images are uploaded in batch, a work is automatically named after the file `,
  MoTiiEDq: `Title of Work `,
  yaRgDcPR: `Enter `,
  ixBTTIpe: `Directory `,
  GGtMJcaA: `Select a Directory to Save Work `,
  MRrACfob: `Project Label `,
  KbsubBfg: `Select `,
  euySqISB: `Created by `,
  mgjAOedz: `(Enter a valid email address, or the transcoding process could be affected) `,
  kpbtxKBF: `Enter a Valid Email Prefix `,
  AoDmguBf: `Asset Type `,
  GWCIGZkf: `Copyright Free Resource `,
  WpueVdEo: `Show Available for Commercial Use Sign When Applicable `,
  vqrBWqXP: `Effective Person-Day Value `,
  gHnzApfC: `Enter Value `,
  JrFsoybq: `Custom Label `,
  adwccqaU: `Enter Custom Label and Press Enter to Add `,
  EJEcADkr: `Work Description `,
  ZZndrlRc: `Enter Description `,
  yWqfpnmq: `Unable to Create `,
  OFmzKZkJ: `Created `,
  mKGBpUuj: `Upload {x} `,
  NbAVSYQB: `{x} Note `,
  oupbLaLh: `{x} File `,
  poNNkcos: `Compress the files directly without saving them in a separate folder beforehand `,
  bxHDnDPX: `This {x} will be created under Class {y} `,
  cUeExUrC: `Assets `,
  nkOBUDaQ: `Asset Dashboard `,
  YlpbFYcm: `Filter by Type `,
  ZuHaMrKc: `Select Type `,
  aTrJDVfH: `Enter a Name to Search `,
  rnFgaqWc: `Create Asset Library `,
  mDuoqqpB: `Asset Library `,
  VvRacnzZ: `Once deleted, all data in the asset library will be removed. Proceed with caution `,
  NFrtNmOa: `Deleted `,
  aISmpILb: `Saved `,
  zvpBcXiW: `Save Prompt `,
  ZkXzAtma: `Select a Prompt Library to Save Prompt `,
  qsZkQqUk: `Project Prompt Library `,
  UYFOaXKY: `Custom Prompt Library `,
  zrGScdGc: `Select a Class `,
  cnYvAdSB: `Select a class to save prompt. If no classes are selected, the prompt will be saved in the root directory of the prompt library `,
  ffuroSuY: `Prompt Name `,
  dyjvsJWR: `Example: Three-view `,
  HwewQWiW: `Prompt Cover `,
  bZgnDZaY: `Positive Text Prompts `,
  MdJBqbZI: `Negative Text Prompts `,
  VlOKWAWe: `Parameters `,
  JEGeLZDX: `This prompt will be created under Class {y} `,
  JlAUvrgS: `This Prompt Will Be Created Under the Root Directory of the Selected Prompt Library `,
  hyioMVow: `Asset Library Owner `,
  PCaRsZcb: `Asset Library Admin `,
  lOOHuceZ: `Asset Library Description `,
  uTvlUVjO: `Last Modified `,
  UsmQtEmR: `Edit `,
  LAttByQx: `Delete `,
  VMrkWhZS: `User Group `,
  qihCHtAY: `User `,
  wMKfJrDT: `Create  `,
  GkVyaBxW: `Select at Least One Admin or Admin Group `,
  TeASSVCu: `Unable to {x} `,
  qrawqSiI: `Action Complete `,
  RKIjvdKm: `{x} Asset Library `,
  YbIuwSiG: `Cancel `,
  lceBybCo: `Uploading… `,
  MzuEqCFV: `Create `,
  HgptwkMX: `Name `,
  UaQZCSWO: `Enter Asset Library Name `,
  WlNRpOlS: `Type `,
  TOASIiOg: `Description `,
  WrtxbPLp: `Enter Description `,
  aIZDTfCP: `Asset Ownership `,
  xfEbsSwK: `Select Asset Ownership `,
  XngKAkVS: `Admin `,
  yeIsMHlE: `Select Asset Ownership First `,
  APrsTDHQ: `Select Asset Library Admin `,
  yryoWYjS: `Member `,
  qQANBKXK: `Select Asset Ownership First `,
  ZpssKxMd: `Select Asset Library Member `,
  TTeueCLr: `Download `,
  ugVeKDUX: `Delete `,
  mlLfQOOL: `Share to Muse `,
  SkNNsAvj: `Move `,
  GSMEKhtf: `Score `,
  eLjnWPDc: `Rename `,
  soGkQJxt: `OK `,
  nEAaNjfX: `Cancel `,
  aJKgjPZW: `Downloading... `,
  gblWRZXN: `Input label and press enter to add. input no more than {x} characters `,
  vSOAVfOn: `DreamMaker Model `,
  vdxlVnLJ: `Project Model `,
  DnRDCBQF: `All  `,
  AODBGZwb: `User Group `,
  DxPTWCwT: `User `,
  EsGDTOPz: `Update Complete `,
  sRrDvxty: `Update Error `,
  zoqbrgIN: `Once closed, this will not be shown on Creation Platform `,
  yzdimqCe: `Click to View Details `,
  JLJCnlRR: `Upload Complete `,
  CDwQMhmd: `Uploading… `,
  uNupcpDa: `Click to Copy Model Name `,
  IXAZnPeX: `Saved `,
  OGMTzuNe: `Existing Label `,
  Dszdutnd: `Keep at Least One Admin `,
  hYwLKKiC: `You Can Upload up to 4 Artworks `,
  htNWrYnj: `Unsaved Content Detected `,
  uJydLhgZ: `Admin `,
  ufLpBcmW: `Remove {x}? `,
  UdLzITWt: `Remove `,
  xamSSRGU: `Cancel `,
  HJotRSPW: `Remove `,
  hgGjbWEB: `User Name `,
  oShtmihp: `Actions `,
  xpAcldVo: `Delete Model `,
  KzyzQNTE: `You Are Trying to Delete: `,
  zdNoYouP: `Once deleted, all data under this model will be removed. Enter {x} to confirm `,
  tZIIAkFO: `to confirm `,
  AcTCiQse: `Enter DELETE `,
  XVIEmmxJ: `Cancel `,
  MVeYJoxu: `OK `,
  RoxNXPVT: `Enter DELETE `,
  EtOnVzfe: `Unable to Delete `,
  LwCFgThx: `Deleted `,
  EWczkSZI: `Model Details `,
  kurEPXpN: `Delete Model `,
  JtdAwaKs: `Descriptions `,
  RwpVehGO: `Trigger Words `,
  FmKFuVfX: `Model Code `,
  QBwUGFNL: `Member List `,
  hjABRAHe: `Label `,
  HqZETOZE: `Artwork Preview `,
  NaMygqPk: `Delete This Artwork? `,
  gPilvxlA: `Delete `,
  yveZKhfz: `Cancel `,
  EUzWWfuB: `Cover `,
  yYLoTRxt: `YAML Files `,
  kgpMwcUp: `No Data Uploaded `,
  DetqMgjF: `Add Members `,
  dQccyAJf: `Select at Least One Model First `,
  TncCEBWV: `You are not authorized to edit any of the selected models. Select at least one model that you have permission to edit `,
  BwcMtbcn: `You are not authorized to edit some of selected models `,
  UJjulpKA: `Edit the Following Models? `,
  DQlXunNk: `Select at Least One Model First `,
  ZiVAVlLq: `Model `,
  vsXwJuWl: `About to delete the following models that you are authorized to edit. Proceed with caution `,
  DYUVuFRi: `Batch Deleting… `,
  QkhVexUR: `Deleted `,
  mluFgASm: `Modify Member List `,
  dpeTwzkB: `Delete `,
  IiSmcPIF: `Batch Modify Model Members `,
  RwHrDZbU: `Batch Modifying… `,
  NnFvdJrn: `Modified `,
  MvugJbbA: `Required Field `,
  eNMbCjlT: `Up to 20 Characters `,
  GoDWLThr: `Class Name `,
  rBYchiEq: `Associate DreamMaker Model `,
  hoPomRjI: `Associate Project Model `,
  QTtQPfrm: `Class Details `,
  LpJgVoAX: `Unable to Delete `,
  NhKqnKqq: `Once confirmed, this class will be deleted. Proceed with caution  `,
  yLKlZova: `Class Name `,
  DAERJkJa: `Time Created `,
  ZcsamZSO: `DreamMarker Model `,
  nSZghdhf: `Project Model `,
  OdMzkHWc: `Action `,
  naFwqpVK: `Edit `,
  BAbQhwCm: `Tag Name Already Used `,
  KTTQnAqn: `Action Complete `,
  DpkdCEIL: `Unable to Complete Action `,
  qCrmiZgV: `Model Class `,
  kNbIGPPx: `New Class `,
  HBIpEnJe: `Class: `,
  PtaKUlBU: `Format: `,
  kqYLtQqO: `Drag Select with Mouse or Press Shift and Click on The Non-image Area to Select More `,
  UcPXsqBv: `Select All `,
  AflWZvtW: `Enter The Model Name and Label to Search `,
  rzgEaYoL: `Model Class `,
  dATBmhrn: `Model Class `,
  RjlaBPFA: `{x} Selected `,
  BlsAmztW: `Image Uploaded `,
  YhOoJvaa: `Unable to acquire address for image upload `,
  xcjfBVNZ: `Error in acquiring address for image upload `,
  mduQMYpt: `Uploading… `,
  gvTwmApv: `Edit Cover `,
  QwdwBmOX: `Select One of The Existing Artworks as The Cover `,
  AuZWlIDB: `Click the Image to Crop `,
  mXiPzUGA: `The Current Work is empty. Please upload the work first then select one of them as the cover. `,
  kZFnUNmW: `Please Check the File Size (No More Than 10GB) `,
  rwjpHkcs: `Uploading. Please Do Not Close. `,
  rTeFreBA: `Checking files. This may take a few minutes. `,
  NCAaDRrb: `This name already exists in the model library. `,
  XJGnhFuC: `Please modify the model name and try again. `,
  IMjveMLH: `Uploading. This process takes some time. Closing or refreshing will interrupt the upload… `,
  HYnaNBDy: `Uploaded `,
  QFQaegYw: `Upload complete. Large models requires some time to complete loading. Refresh the model list to view it later. `,
  tVoboNTI: `This model already exists in the library. To modify or delete it, please contact the platform admin. `,
  WRoGdqUh: `Upload Model `,
  aMKgnOAP: `Support Only ckpt or safeTensor `,
  xBExHtPX: `Cancel `,
  mWPFxoaO: `Uploading… `,
  mHMgwNTc: `Confirm `,
  NpKxduGC: `What model do you want to upload? `,
  GGfVGTpp: `What model do you want to upload? `,
  vSUeAyzx: `Model Name `,
  xJxkjTmZ: `There is an existing model with the same name. Please modify the model name. `,
  pwpjGkeE: `We strongly recommend naming it in such format as G11_ Lora_ GUI `,
  GWazdNDN: `Descriptions `,
  GLaWvzNH: `Enter Model Description `,
  JTLVDfpU: `Label `,
  vovNBrQk: `Label Name should be no more than {x} characters `,
  qhMTdacO: `Input label and press enter to add. Input no more than {x} characters. `,
  YdTCziHM: `Trigger Words (Trigger_words) `,
  yVMzFAeo: `Enter Trigger Words `,
  jUUIeGqE: `Upload Model File `,
  zmLuQvyc: `Pack all files directly. Do not put them into a folder then compress it. `,
  qVOyGEYR: `Click or Drag Files to This Area to Upload `,
  MjTUDDyg: `Support Only .safesensors or. ckpt formats. (File Size Less than 10GB) `,
  wTXifvzB: `Upload YAML File `,
  NQawNiES: `Click or Drag Files Here to Upload `,
  mtsOGIyq: `Support .yaml Format `,
  IwGjSEtE: `Upload Sample Artworks `,
  UcKzLiiW: `Support to Upload up to 4 Artworks `,
  NTeFyWFb: `Click or Drag Files Here to Upload `,
  wefkdotK: `Support Formats such as png, jpg, and jpeg `,
  CIIkmHoi: `Select One Randomly as The Cover `,
  XZQwdQUH: `Select Images `,
  sGtQpJag: `The size exceeds 10M. Please check the images for upload. `,
  hKNyFlDf: `Upload Artworks `,
  AVpJumPY: `You can upload up to {x} artworks `,
  cvkRfXQR: `Upload failed. Please upload again. `,
  udghCBUc: `Upload Complete `,
  blCdbCZJ: `Drag the Files Here `,
  JcjRmAoW: `Click Here `,
  pWZMUyGj: `Upload `,
  egtJguiu: `Unable to create an instance. Please try refreshing the page. If it still fails after refreshment, please contact Liu Qi (liuqi17@corp.netease.com). `,
  nMSUDXpx: `Starting. Please Wait… `,
  UNAPWLjw: `The size exceeds 10MB. Please check the uploaded images. `,
  AWFnlNsN: `Only images in formats such as png, jpg, jpeg and svg can be uploaded `,
  eouokHmZ: `Project Name is Required `,
  zaSrowZv: `Up to 20 Characters `,
  iikQBoIq: `Cost Center is Required `,
  qJlZRrvR: `Project Name is Required `,
  XnSTsAzB: `Select At Least One Admin `,
  lgDwgRlJ: `Unable to Modify `,
  DsgJigmn: `Modified `,
  VwiebFFr: `Unable to upload. Please upload again. `,
  PmNmRncL: `User Group `,
  tRBWvdxn: `Number of GPU Cards `,
  eEEFbtkm: `Admin (Contact) `,
  fBVleSdt: `Member `,
  eiBegDrs: `Cost Center `,
  GIZWszyw: `Project `,
  wBWLtPHJ: `Edit User Group `,
  yDrZvLia: `Group Name: `,
  ZPckwwkV: `Enter A Group Name `,
  huUQsWWA: `Admin: `,
  eCTQRXRe: `Enter Admin Info `,
  HlzbeOcA: `Members: `,
  JsAaDpSo: `Enter Member Info `,
  urWbbHmR: `Search `,
  xYlHHUpd: `Reset `,
  NqmFCIpz: `Group Name `,
  oEYmaRtM: `Number of GPU Cards `,
  ajQlovCg: `Cost Center `,
  rTkrdYzW: `Admin (Contact) `,
  DCqmldwT: `Member `,
  mHQHGhju: `Time Created `,
  SsCQPpNx: `Project `,
  mZblvOYL: `Action `,
  bSeNKfij: `Edit `,
  MyrkSnFr: `Sure to Perform This Operation? `,
  bTAdCjeP: `Confirm `,
  wDCuhchh: `Cancel `,
  lkEWNXpC: `Delete `,
  DVLQNZYf: `Unable to Delete `,
  waBpvmjQ: `Deleted `,
  ZDACkTNp: `Public `,
  dVZoWPhN: `New `,
  YdyTXlZY: `Copy `,
  ZVtxmUye: `Paste `,
  HGatJPfD: `No Prompt Selected `,
  tVpOYtgP: `Prompt Info Copied `,
  HCcysrab: `No Prompt Info Found `,
  dETxAWlr: `Action Complete `,
  fwORsdJH: `This library is provided by KM `,
  lYJevGZS: `DreamMaker Text Prompts `,
  OJnXpdOC: `Project Text Prompts `,
  mYodcVkc: `Custom Text Prompts `,
  ygcSBWEC: `This image has no prompt info `,
  hzfNQRsL: `Click to Upload Images to Read Info `,
  iqUHEbhN: `Template for Text Prompt Library Batch Import `,
  UFKGiDrr: `Batch Import Prompts `,
  cCRBHWaq: `No class for this library. Please create a new class. `,
  sZkeJrsX: `Name is Required `,
  SjNoyWqa: `Up to 50 Characters `,
  tUBuTDDR: `Add `,
  zWlyfJqv: `Override `,
  quaBahpI: `Prompt `,
  kixYECmV: `Add/Replace Cover `,
  NkOGJUfg: `Copy All Parameters `,
  aRjgvMDs: `Save `,
  hkySijWk: `Override All `,
  NpLEjuGU: `Enter Positive Text Prompt `,
  WPvWtcCd: `Enter a Parameter `,
  ZXMsSNPA: `In this area, you can save the content below as new prompt. `,
  mRVBzgwG: `Auto Cut `,
  tnWfhlAI: `Save as New Prompt `,
  OFKKeBMs: `Save Prompt `,
  uMdFUbeg: `Upload/Replace Prompt Cover (Optional) `,
  CJVrEFNm: `This prompt will be created under Class {x} `,
  FNPRWLCd: `This prompt will be directly created under the current library. Recommend to create it under a subclass. `,
  wbRqAGFs: `Search in The Current Directory (Prompt Name, Positive Text Prompt, Negative Text Prompt) `,
  YxXskFZG: `Creation Platform `,
  VxtMciIi: `Creation Record `,
  CxgVRNOY: `Assets `,
  DUsIQIaD: `My Models  `,
  bCIfXyos: `Text Prompts `,
  eBehLmrk: `Training Platform `,
  RpBPaYsE: `User Groups `,
  DKUCIgKM: `Node Flow `,
  wMAoWiql: `Model Type `,
  ITFpLqkW: `Base Model `,
  WrMRYasG: `Default `,
  GOpPuTQE: `Training Material Resolution `,
  sfmcjwVu: `Training Dataset `,
  HZzVbwwG: `Adaptive Aspect Ratio? `,
  aLIaENDh: `Yes `,
  KbtUpdNi: `No `,
  jwaaOZzg: `Image Label Settings `,
  YuWEfWgX: `Training Details `,
  BGjtotGh: `Details `,
  aclMFGDt: `Training Cycle (Epochs) `,
  jVqCojnI: `Dimensions (network_dim) `,
  VgyKgEnk: `Weight (network_alpha) `,
  DfOQEMHA: `Noise Offset (noise_offset) `,
  cYMDYrRw: `Optimizer (optimizer_type) `,
  NQOjtBua: `Shuffle Descriptions Randomly (shuffle_caption)? `,
  GihwrBzx: `Yes `,
  TwQZNxKf: `No `,
  jLLytVoX: `Keep the First Few Descriptions Intact `,
  aceQsfdP: `Discard Part of Description Randomly (caption_dropout)? `,
  WsgHPVmg: `Yes `,
  lhQWHiGH: `No `,
  rBGYzOIa: `How many epochs away to discard once? `,
  EBAdltTg: `Proportion per Discard (%) `,
  IAAdFGwP: `Train Text Encoder? `,
  socdNqPG: `Yes `,
  EyuilLgI: `No `,
  ubdcbAYa: `Number of Epochs Before Stopping the Text Encoder Training `,
  CZzfJAnl: `Learning Rate Adjustment Strategy `,
  VirgjbKC: `Restart Times `,
  ZgiIrhJl: `Save Intermediate Result Models? `,
  mAqlkRaS: `Yes. Save Every {x} Steps `,
  cpfZCUmf: `No `,
  JXktVEuV: `Use DreamBooth Mode? `,
  JnpMzevm: `Yes `,
  JTpQUfjY: `No `,
  qfpOsYWZ: `Regularized Weight (prior_loss_weight) `,
  bdaVbdVm: `Subject Class Description (Class Prompt) `,
  eMwhOXnj: `Copy `,
  onQNxZeM: `Number of Regularized Images `,
  cRPTwHOc: `Unable to find training dataset `,
  jESttAUF: `Basic Settings `,
  BezCypTp: `Positive Testing Text Prompts `,
  HuSxaAdz: `Copy `,
  bCdFHHBa: `Negative Testing Text Prompts `,
  nZVjsbEh: `Copy `,
  fegWxMvE: `Advanced Settings `,
  sPuZeJNb: `Base Model and Training Data `,
  XcMxDDtK: `Basic Info `,
  xNchKlCB: `Annotation Settings `,
  jkmqzNTV: `Test Settings `,
  PZIjeBpi: `Advanced Settings `,
  hgemACWh: `AI will learn the content of the image based on the basic resolution of the image. Select a proper resolution according to your expectation on the AI accuracy. Usually, the larger the resolution is, the better the AI learning result will be but the longer it will take for training. And it will also affect the AI computation rate upon actual application. (Example: If the image dimension of your training material is 512*640, select 512 as the training resolution.) Our training algorithm support materials of various aspect ratios and auto-compress them, making them close to the target resolution. The auto-compression algorithm won't further trim nor deform the images.  `,
  vcJoVNMy: `Default `,
  mTIMExTZ: `Check the New Form `,
  NzObormH: `Uploading Training Dataset… `,
  hgucTBlw: `Unable to Upload Dataset:  `,
  lQnwQlhh: `Check the dataset first. Upload dataset from existing training datasets or local files. `,
  UjfRUCCM: `Submitting… `,
  xZdyMvyu: `Created `,
  WxYxaRJy: `Error. Unable to Create `,
  QYZIHLLN: `Submitting. Please do not close. `,
  ATTnxGTY: `Cancel `,
  HOiNVMGq: `Confirm `,
  ercswgnf: `Create Training Task `,
  eOCYXKHH: `Copy Training Task `,
  ROguGGsA: `You can click {x} to learn about the specific function of each parameter. `,
  IZokwTfO: `Training Platform Best Practices `,
  rpwLpzVY: `to Understand the specific function of each parameter. `,
  xTqsWLsA: `What kind of model do you want to train `,
  WxzQjzuC: `Select `,
  KDQsDRvi: `Base Model `,
  YTvyaauQ: `Select a Base Model `,
  xjxYdnsy: `Select `,
  kdGKdwNb: `Training Material Resolution `,
  KEZqKgqB: `Select `,
  GYIfhWOl: `Upload Training Sets `,
  ahKhSohk: `Upload from Existing Datasets `,
  REuguzsj: `Upload from Local `,
  cJVeUSPA: `1. Pack all files directly. Do not put them into a folder then compress it. `,
  VNQtbdsI: `2. Training sets uploaded locally will be stored in private asset library by default, under the default training set class. `,
  UdwThCym: `Upload Datasets `,
  oVCLCBmP: `Select a Dataset `,
  mdzipdBH: `Adaptive Aspect Ratio? `,
  iEqzANQS: `Disable this option if the training material is with standard resolution. Otherwise, enable it. `,
  HWKwffpu: `Training Task Name `,
  uoiazxoL: `Enter a name for the training task. Enter no more than {x} characters. `,
  DxjBMBFX: `Image Label Settings `,
  cfKWfkpC: `Select settings `,
  BTZLOKgG: `Add Prompts to Generate Test Images with Your Model `,
  XOWUklTd: `Positive Testing Prompts `,
  jzHsclQw: `E.g. masterpiece, best quality, a cute girl, blue eyes, brown hair, etc. `,
  ZcRAdFAR: `Negative Testing Text Prompts `,
  MWazJnSy: `Enter `,
  kpANxOdj: `Runtime Parameters for Training Tasks. Leave as default if you are just getting started. `,
  qAcOmxgv: `Enter `,
  hurQyBzj: `Enter `,
  PzcBIpCp: `Training Cycles (epochs) `,
  nwrQouSv: `Enter Number of Training Cycles `,
  FImSftdE: `Enter Batch Size `,
  ThKGHgVp: `Dimension (network_dim) `,
  LIqrOFLX: `Enter Dimension `,
  vVfpHbSb: `Weight (network_alpha) `,
  cvYzouGM: `Enter Weight `,
  DCYQarJh: `Noise Offset (noise_offset) `,
  DXYVTVRh: `Enter A Value for Noise Offset `,
  VtvRpGvC: `Enter clip_ Skip `,
  pqlCDvTU: `Optimizer (optimizer_type) `,
  FXudWqOC: `Select `,
  euPrFGPK: `Use DreamBooth Mode? `,
  eoCFCExu: `Subject Class Description (Class Prompt) `,
  bJuMdtmN: `A photo of<xxxx>. Replace <xxxx> with A Specific Type `,
  dzyuaumv: `Number of Regularized Images `,
  GnsGrBmm: `Number of Regularized Images. Positive Integer. The max is 500. `,
  VLLBOiNu: `Regularized Weight (prior_loss_weight) `,
  anPLMKdn: `Dreambooth Regularized Weight `,
  FLHRbxMd: `Shuffle Descriptions Randomly (shuffle_caption)? `,
  MmbVZDNY: `By randomly shuffling tag descriptions, training can be somewhat improved. Recommend to only use descriptions named in tag format (i.e. word naming separated by commas). `,
  yEoyhuXm: `Keep The First Few Descriptions Intact `,
  ZaHArGJn: `When starting shuffle_caption, keep the first few words intact. (Applicable when the first sentence of description is a natural sentence or important.) `,
  ohsPunEC: `Enter `,
  URCwOXHk: `Discard Part of Description Randomly (caption_dropout)? `,
  QpYVaMhd: `By randomly discarding part of the descriptions, it is possible to enhance the training effect of the AI model. `,
  nTIfukev: `How many epochs away to discard once? `,
  IXjVlKiT: `Enter `,
  DGaNjWrp: `Proportion per Discard (%) `,
  xNVkyfnp: `Percentage of Text Prompts Discarded per Time `,
  YLEVigEQ: `Train Text Encoder? `,
  AqpDrZXG: `Number of Epochs for Stopping The Text Encoder Training `,
  GAmEPUkv: `Enter `,
  cLhUdWZj: `Learning Rate Adjustment Strategy `,
  neKPyuFK: `Select a Strategy `,
  bTboZeYB: `Restart Times `,
  INgaNHrA: `Enter `,
  yQUmTZkB: `Save Intermediate Result Models? `,
  grLCxkpF: `How many epochs away to save intermediate result models once? `,
  EJlTFbJw: `An Integer No Greater than The Number of Epochs `,
  ThitFlls: `Terminated `,
  ETbKbKpp: `Error. Unable to Terminate `,
  lhJMaeSF: `Error. Unable to Terminate `,
  zaaGBUqR: `Deleted `,
  iTjfntyh: `Error. Unable to Delete `,
  RBzpXSJH: `Error. Unable to Delete `,
  WHuyVsOB: `Set up a user group on DreamMaker before using Training Platform. After reading {x}, contact Liu Qi (liuqi17) {y} for support. `,
  BgqqNOaZ: `User Manual `,
  CpKnxMKy: `, and contact Liu Qi (liuqi17) `,
  xHTxpCIv: `for support. `,
  nBtOGTXu: `OK `,
  sJhffVuj: `Training Platform `,
  lacNwgPe: `Hi, this is your Training Platform. You can customize and train AI models here `,
  cwsDfOOO: `Label With Image Name `,
  eYastTOY: `Label With Corresponding .txt File `,
  pERWBqIX: `LoRA (Recommended) `,
  nsFumzGx: `Check the new form: No. of epochs before saving the intermediate result model and fill in integers no greater than No. of epochs `,
  xIMvBJxF: `Check the new form: 	Cyclic No. for stopping training Text Encoder is not greater than epochs `,
  lyoovZtk: `Check the new form: No. of epochs before discarding once is no greater than epochs `,
  vCmjSjyK: `Conversion Error `,
  tFlfsfkq: `, name {x} has {y} repetitions `,
  qLmKSPvT: `{x} Years Ago `,
  uEOkQLOG: `{x} Months Ago `,
  WAZHGsYR: `{x} Weeks Ago `,
  TjIKOyDT: `{x} Days Ago `,
  iUaZhYWh: `{x} Hours Ago `,
  upsNsUEf: `{x} Minutes Ago `,
  LRjLDauR: `Just Now `,
  ecanJIym: `Hour `,
  okigvTDW: `Minute `,
  pUBRMdJl: `Second `,
  VJaxORSk: `Add Access to Selected Models `,
  zrooGvRH: `Member `,
  DLWjwSTH: `Error in Aquiring Model Metrics `,
  pObezDrk: `Model Metrics `,
  fDMunwTI: `Evaluate if the Model Meets Usability Requirements `,
  ieOQuifK: `Model file `,
  hxodYLMs: `Training Time `,
  AiAsmhlF: `Final loss value `,
  kuKIGEnK: `Loss-epoch graph `,
  lbdZBjwY: `LR/text encoder-Epoch Graph `,
  NczGgeLV: `Lr/unet-Epoch Graph `,
  QJRlbdLc: `Final Result Model `,
  ZIrBQoCv: `Save to Model Library `,
  cGgFiAxs: `Instructions `,
  CnFGmfZD: `Got It `,
  cTsGsMBy: `Cancel `,
  AsSHuOPV: `Tips: `,
  regOyZMC: `1. You are advised to use company owned or publicly available materials for training; `,
  oBHZNJkq: `2. The sources of training materials should be as broad and sufficient as possible, with possibly a maximum amount of materials and avoiding being from the same author; `,
  pBntcCPw: `3. Do not use illegal content, business secrets, privacy of others, or personal information (especially facial biological information) as training materials. `,
  PbjaPmPd: `4.Before training project materials, make sure you have the consent of project  Art Director or relevant management personnel. `,
  HEzINhiN: `5.Models trained with DreamMaker Self-service Training Platform is only availble DreamMaker online for confidentiality. `,
  ZAtoeJoz: `6. Based on the DreamMakerAi drawing solution, follow APC's guidelines to fill in the value valid man-day for the output. `,
  WVITKUtQ: `7. Innovation results generated from the functions of DreamMaker platform in the future shall be creditted as output based on the DreamMaker. `,
  QhjCbUBE: `Provide Complete Model Name `,
  iLhwyBys: `Duplication in form: {x}. Check the model name suffix `,
  zyIiuDJz: `Check the Name That You Entered `,
  sKDiaItI: `E.g. G11 Icon `,
  DiJhjFxc: `E.g. G11 Icon `,
  BeetFatI: `Name the Final Result Model First `,
  HZmPrjKT: `Sent `,
  AkTpqzbW: `Intermediate Result Model `,
  RlhnjXrI: `Name `,
  uVeMbYFK: `Batch Name `,
  cUmboYuf: `Enter Model Name Suffix `,
  RGivEYwp: `Final Result Model `,
  LblltDZQ: `Name `,
  IpGMaWrl: `Send to 'My Models' `,
  wEyLKRSg: `Confirm `,
  WDdMZsBw: `Before sending to 'My Models', it is necessary to name the model. Recommended format: Project-Purpose `,
  tEartlgQ: `The model has been sent and cannot be sent repeatedly `,
  aYVArEmJ: `The submission is empty, check again `,
  nnJKiefq: `Sent `,
  jjutBIrY: `Unable to Send to 'My Models' `,
  NBzltCPU: `Intermediate Result Model `,
  UzgNgQtj: `If no intermediate result model is saved when creating a new training, only the final model will be displayed `,
  Eisjogdi: `Final Model `,
  CsMFpkFk: `View Image `,
  VZwAlYBV: `Save to Model Library `,
  OsKgraKH: `New Training `,
  CVKjQrrj: `Enter Creator Name to Search `,
  mBwmfwxp: `Enter Training Name to Search `,
  pJVnzqDy: `{x} in the Queue `,
  GWsOtihA: `Starting `,
  jLYJCHWy: `Training Completed `,
  nEWbvXID: `Training in Progress… `,
  WzDGuFEI: `Error `,
  LmzeiBxf: `Starting `,
  EqteSdZD: `Stopped `,
  IrPgnYfG: `Training Details `,
  BdetqmXK: `Copy Training Settings `,
  CFLLvhqp: `Terminate Training Task `,
  MsqzDnER: `This will interrupt the current training task, terminate anyway? `,
  NRXqmnjt: `Confirm `,
  hjyNfmDt: `Cancel `,
  DxHwGVXa: `Delete Training Record `,
  lENVQuPN: `Delete This Training Task? `,
  yZEKXrWH: `Confirm `,
  yIlXJLnK: `Cancel `,
  KPaMuuoA: `Details Not Obtained `,
  wRILsVVZ: `- Training Platform - DreamMakerPro `,
  euhQiHUZ: `Details Not Obtained `,
  WVZOslWT: `{x} in the Queue `,
  itPJEgFq: `Created on {x} `,
  fIQeAqHT: `Sorry! You do not have access to the page. Click below to go to the access application page. `,
  zXolyScr: `Go to Access Application Page `,
  fRULtWyg: `Image Upload Error `,
  cdJNHNUc: `Only images in formats such as png, jpg, and jpeg can be uploaded `,
  mqPxixiK: `Check the file size. File size must be smaller than {x} `,
  cSDXfOLD: `Add the Following Members to the Original Member List `,
  UzGjgVEK: `Overwrite the Original Member List `,
  RbxhtwUE: `Admin and members cannot both be empty `,
  MEGEqNvh: `Add Access to Selected Models `,
  IqBjJIoM: `Select Type `,
  yMSedvIv: `Admin `,
  RcGYvTXm: `Required `,
  TJnLlcBl: `Admin `,
  qGOSZiac: `Member `,
  rMzvghYU: `Downloading… `,
  AZWQiSXa: `Image `,
  kmLphHRY: `Parameters `,
  OZbukzsB: `Parameters `,
  LVwORYkw: `Training Set `,
  hhgJGzZU: `Double Click to Select a Class or Click to View Sub-Classes `,
  LyRaSOMg: `Select Location for {x} `,
  DGgYxPEO: `No Data Available `,
  afJnaTKb: `Select {x} `,
  qzHqJSSB: `Select {x} `,
  zkhdiNub: `No Data Available `,
  rRsjOdBw: `Check the file size. File size must be smaller than {x} `,
  QqeKXJfg: `Click or Drag Files Here to Upload `,
  dRUkbLfe: `Only {x} Format Supported `,
  IaLWfQnH: `File size must be smaller than {x} `,
  bIzIkgjC: `User Group `,
  fKqPqBEr: `User `,
  APTwlgdg: `Move to `,
  dcuwSwjc: `Select a Class First `,
  StmxIiTq: `Upload {x} `,
  yCcfdZAP: `{x} Uploaded `,
  sgLFivEf: `Completed `,
  qQpqTCHm: `{x} Exceeds {y}. Please Check Again `,
  CuMxIfbg: `Uploading… `,
  ixGMwnKS: `Unable to Upload. Please Try Again `,
  IFjXnFme: `Upload Completed `,
  hvYsnoOZ: `Drag Files Here or {x} to Upload `,
  fZgjgeNe: `Click here `,
  bisqPrUo: `Upload `,
  cmCqgzfh: `File Size Cannot Exceed {x} `,
  GUsymvDU: `Positive Text Prompts `,
  RWTtwCbe: `Negative Text Prompts `,
  iBtjNlfi: `Plot Parameters `,
  wiGnmgtO: `Fill at least one of these fields: Positive Text Prompt, Negative Text Prompt, and Plot Parameters `,
  NlFKCvjl: `The modifications are not saved. Save them? `,
  sjRYxSFk: `Save `,
  VHxpSPRO: `Do Not Save `,
  MsMqpzSn: `Popo account does not exist `,
  MkQkZdHH: `No POPO account was found for this user `,
  cWfYnuMS: `No POPO account was found for this user `,
  KjtHTXdG: `Folders `,
  NGYdYScG: `Class `,
  nzzCSmdf: `You can create up to 5 levels of {x} `,
  HdGSfSzJ: `Create {x} `,
  wfyoFxar: `Deleted `,
  zKLNaluh: `Unable to Delete `,
  KyqYxtXe: `Search {x} `,
  vUwDUFDh: `Delete the value in the class search box first `,
  dFtxetto: `New Root {x} `,
  MjGavqWP: `{x} Unavailable `,
  FWveOZYM: `Rename `,
  TKePTGYU: `Delete `,
  UwVnceYe: `Once confirmed, all data under {x} and its sub{x} will be deleted. Proceed with caution. `,
  OSqUvceO: `More Actions `,
  rPPIKncf: `{x} Name Is Required `,
  FbHcDbRO: `{x} with the same name already exists `,
  HXvChkdr: `Server Error. Please Contact the Admin. `,
  sxqdtVox: `Error in Request (400) `,
  IneAJOkq: `Unauthorized Access. Please Log in Again (401) `,
  ojiXoZVk: `Access Denied(402) `,
  qOxHojRZ: `Error in Request(404) `,
  SeaBhccy: `Request Timeout (408) `,
  SxhVfYOE: `Error in Server(500) `,
  hWahajBZ: `Service Unimplemented (501) `,
  MSNfsLmn: `Error in Network(502) `,
  HxLACVyQ: `Service Unavailable (503) `,
  gAOkijxZ: `Network Timeout (504) `,
  ODNlMMym: `HTTP Version Not Supported (505) `,
  OTEdolWz: `Connection Error ({x}) `,
  lXjCDufv: `Check Your Network or Contact the Admin `,
  DlbpTLTv: `Canceled Duplicate Requests: `,
  grASkDlp: `Unable to Switch Instances `,
  OlmUwgDq: `Current Group: `,
  ftMRLjoq: `→→→→ Vote for us at Art Innovation Award, we need your support←←← `,
  aHxWMIqm: `Muse Tool ID: AI00010979HH `,
  eOlMhgNe: `AIGC Knowledge Library `,
  GaaRCLUt: `POPO Group `,
  PIUnAKjn: `You do not have access to this platform. Please contact the POC or {x} for access. Pricing plan:{y}. `,
  tplrTHCB: `DreamMaker Designer Liu Qi `,
  eOMfFxLn: `Activate usage access. Here is pricing. `,
  dEHyJnci: `Developed jointly by the Technology Center and the Art and Design Center, AILAB provides support for AI related capabilities.  `,
  xprZItNH: `Required Field for Admin `,
  kDFkGphZ: `Enter or Select `,
  hohcTvHE: `Enter or Select `,
  AVyQifaJ: `Mock result `,
  UHKCqOlY: `Copied `,
  JnVOjSOr: `Unable to Copy `,
  ozZUjKmE: `Copied to Clipboard `,
  bOnDaTds: `Error `,
  UtylcJlm: `Copied `,
  dcnKjCsw: `byte `,
  LgBVMxWb: `model `,
  SpOBqlNa: `Delete {x} `,
  ojDdlkCA: `Enter {x} to Confirm `,
  eIlAFyQl: `Confirm `,
  XWhkNVnO: `Enter DELETE `,
  CsQhhnXR: `Cancel `,
  OoONqqTB: `Confirm `,
  DgAGaBIS: `Enter DELETE `,
  SgMLlFmN: `Value cannot be empty `,
  ryHeMMva: `Error value: `,
  JDxkErLJ: `Cancel `,
  QtatyAxz: `Confirm `,
  NCgcyOwh: `Jointly developed by Technology Center and Art Design Center. AILAB provides AI-related supports. `,
  ddGNxRnL: `You have not joined the experience user group. Please contact the administrator to join the user group.  `,
  allclass: `All  `,
  unclass: `Unclassified `,
  mymodel: `My Models  `,
  modelslogan: `Hi, this is your AI model repository. If your project has customized models, please contact the Admin to obtain permissions. `,
  dwqfexOo: `{x} Items in Total `,
  xPdHFtbH: `Associate Model `,
  aZpaEQoG: `Sending... `,
  ZRVOtgFJ: `Send to Project Model `,
  VTxKlALo: `Upload Local Model `,
  JhbxSzQJ: `Private Model `,
  vufSBmLs: `Send to `,
  tkLGcIWW: `From: `,
  zLSLUNEH: `Overview `,
  uohcBqGc: `Heads up `,
  HTHLJrQN: `The portal to Creation Record will no longer be available. To view image records, please go to Assets > Image, and select a library from the dropdown menu. `,
  YwkdAECn: `Model Source `,
  LQTnalbv: `The model name "{x}" is already in use by another user. Choose a different name and try again `,
  VZGHOvsI: `Configuration Completed `,
  PSMAuCbp: `Make Models Available for Download `,
  fuYDfyuO:
    `Please select the model that needs to be configured as downloadable`,
  laifVLlA: `Please select `,
  khxaHxBl: `Send the Following Authorized Models? `,
  bMAMDcaS: `Make Models Available for Download `,
};
